#.travis.yml

language: node_js
node_js:
  - "8.9.3"

branches:
  only:
    - master

before_script:
  - cd ./dbTrainingEnroll
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install

script:
  - ng build

after_success:
  - firebase deploy --token 1/MbsP3R6c3sncU0tN_2KuBkhlTXppnxn6kiZ6B5vwG-8Wo28uZdP68UBQyeOarfQ8

notifications:
  email:
    on_failure: change
    on_success: change